# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 指定我们刚刚创建的 Flutter 模块的路径
flutter_application_path = '../flutter_module'
# 拼接脚本文件的路径: .ios/Flutter/podhelper.rb
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'OCProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCProject
  install_all_flutter_pods(flutter_application_path)

end

post_install do |installer|
  flutter_post_install(installer)
end

